name: Export SVG from Figma
on: [push, pull_request]
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node setup
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: cd script; npm install
      - run: cd script; npm run start FIGMA_TOKEN={{ secrets.FIGMA_TOKEN }}
